HWDIR := ../../../dvk/MOOC/PrincetonAlgorithms


ln_hw:
	ln -sf $(HWDIR)/Percolation.py
	ln -sf $(HWDIR)/PercolationStats.py

3s1k:
	ThreeSum.py ../../thirdparty/1Kints.txt

clean:
	rm *.pyc

clobber:
	make clean
	rm -r *.png
