
# Example from Algs1, Programming Assignment #2
wk2_subset:
	echo A B C D E F G H I | Subset.py 3
	echo AA BB BB BB BB BB CC CC | Subset.py 8
	echo A B C D E F G H I | Subset.py 3

clean:
	rm *.pyc

clobber:
	make clean
	rm -r *.png
